---
- name: this playbook is to create a new file or directory
  hosts: all
  #  become: true
  #  gather_facts: no 
  tasks:
    - name: create a directory
      file:
        path: /home/ansadmin/dir1
        state: directory
