---
- name: this playbook installs packages on slaves
  hosts: appservers_amznlnx
  #  become: true
  tasks:
    - name: install package
      yum:
        #        name: ['git', 'make', 'gcc', 'wget', 'telnet', 'gzip']
        name: "{{ item }}"
        state: installed
      with_items: 
       - git
       - make
       - gcc
       - wget
       - telnet
       - gzip
