---
- name: install apache2 on ubuntu
  hosts: dbservers_ubuntu
  become: true
  tasks:
    - name: install apache2 
      apt:
        name: apache2
        state: present

    - name: start apache2 service
      service:
        name: apache2
        state: started

