---
- name: install apache2 on ubuntu
  hosts: all
  become: true
  vars:
    port: 8082
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      notify: start apache   
 
    - name: install package
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
      notify: start httpd service

    - name: copy index.html to slaves
      copy:
        src: /opt/ansible/index.html
        dest: /var/www/html
        mode: 0666

    - name: Ensure the default Apache port is {{ port }}
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen {{ port }}
      when: ansible_os_family == "RedHat"
      notify: restart httpd service

    - name: Ensure default apache2 port is {{ port }}  on ubuntu
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        insertafter: "# /etc/apache2/sites-enabled/000-default.conf"
        line: Listen {{ port }}
      when: ansible_os_family == "Debian"
      notify: restart apache2 service

  handlers:
    - name: start apache
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: restart httpd service
      service:
        name: httpd
        state: restarted

    - name: restart apache2 service
      service:
        name: apache2
        state: restarted
     

