---
- name: this playbook uninstalls apache package on slaves
  hosts: all
  become: true
  tasks:
    - name: stop httpd service package
      service:
        name: httpd
        state: stopped
      when: ansible_os_family == "RedHat"

    - name: uninstall httpd service
      yum:
        name: httpd
        state: removed
      when: ansible_os_family == "RedHat"

    - name: stop apache2 service on ubuntu
      service:
        name: apache2
        state: stopped
      when: ansible_os_family == "Debian"

    - name: uninstall apache2 service on ubuntu
      apt:
        name: apache2
        state: absent 
      when: ansible_os_family == "Debian"
